name: zakat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  http: ^1.2.0
  mysql1: ^0.20.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - images/
#  fonts:
#    - family: segoe-ui
#    - asset: fonts/segoe-ui-4-cufonfonts.zip/Segoe UI.ttf